#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2022.2 (64-bit)
#
# Filename    : system.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Wed Feb 14 13:13:33 CST 2024
# SW Build 3671981 on Fri Oct 14 04:59:54 MDT 2022
#
# Tool Version Limit: 2022.10 
#
# usage: system.sh [-help]
# usage: system.sh [-lib_map_path]
# usage: system.sh [-noclean_files]
# usage: system.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'system.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Set vlogan compile options
vlogan_opts="-full64 "

# Set vhdlan compile options
vhdlan_opts="-full64 "

# Set vcs elaboration options
vcs_elab_opts="-full64 -debug_acc+pp+dmptf -t ps -licqueue -l elaborate.log "

# Set vcs simulation options
vcs_sim_opts="-ucli -licqueue -l simulate.log "

# Design libraries
design_libs=(xilinx_vip xpm xil_defaultlib xbip_utils_v3_0_10 axi_utils_v2_0_6 fir_compiler_v7_2_18 util_vector_logic_v2_0_2 xlslice_v1_0_2 xlconstant_v1_1_7 generic_baseblocks_v2_1_0 axi_infrastructure_v1_1_0 axi_register_slice_v2_1_27 fifo_generator_v13_2_7 axi_data_fifo_v2_1_26 axi_crossbar_v2_1_28 lib_pkg_v1_0_2 lib_cdc_v1_0_2 axi_lite_ipif_v3_0_4 interrupt_control_v3_1_4 axi_iic_v2_1_3 dist_mem_gen_v8_0_13 lib_srl_fifo_v1_0_2 lib_fifo_v1_0_16 axi_quad_spi_v3_2_26 xlconcat_v2_1_4 axi_vip_v1_1_13 processing_system7_vip_v1_0_15 proc_sys_reset_v5_0_13 axi_protocol_converter_v2_1_27)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "system.sh - Script generated by export_simulation (Vivado v2022.2 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../bd/system/ipshared/a40c" +incdir+"$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/a40c" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xpm $vlogan_opts -sverilog +incdir+"$ref_dir/../../../bd/system/ipshared/a40c" +incdir+"$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/a40c" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "/tools/Xilinx/Vivado/2022.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "/tools/Xilinx/Vivado/2022.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
    "/tools/Xilinx/Vivado/2022.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "/tools/Xilinx/Vivado/2022.2/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/system/ipshared/a40c" +incdir+"$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/a40c" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_cdc_sync_active_0/sim/system_cdc_sync_active_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xbip_utils_v3_0_10 $vhdlan_opts \
    "$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/364f/hdl/xbip_utils_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_utils_v2_0_6 $vhdlan_opts \
    "$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/1971/hdl/axi_utils_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work fir_compiler_v7_2_18 $vhdlan_opts \
    "$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/d172/hdl/fir_compiler_v7_2_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_fir_interpolation_0_0/sim/system_fir_interpolation_0_0.vhd" \
    "$ref_dir/../../../bd/system/ip/system_fir_interpolation_1_0/sim/system_fir_interpolation_1_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work util_vector_logic_v2_0_2 $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/system/ipshared/a40c" +incdir+"$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/a40c" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/3d84/hdl/util_vector_logic_v2_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/system/ipshared/a40c" +incdir+"$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/a40c" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_logic_and_0_0/sim/system_logic_and_0_0.v" \
    "$ref_dir/../../../bd/system/ip/system_logic_and_1_0/sim/system_logic_and_1_0.v" \
    "$ref_dir/../../../bd/system/ip/system_out_mux_0_0/sim/system_out_mux_0_0.v" \
    "$ref_dir/../../../bd/system/ip/system_out_mux_1_0/sim/system_out_mux_1_0.v" \
    "$ref_dir/../../../bd/system/ip/system_rate_gen_0/sim/system_rate_gen_0.v" \
    "$ref_dir/../../../bd/system/ip/system_cdc_sync_active_1/sim/system_cdc_sync_active_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_fir_decimation_0_0/sim/system_fir_decimation_0_0.vhd" \
    "$ref_dir/../../../bd/system/ip/system_fir_decimation_1_0/sim/system_fir_decimation_1_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/system/ipshared/a40c" +incdir+"$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/a40c" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_out_mux_0_1/sim/system_out_mux_0_1.v" \
    "$ref_dir/../../../bd/system/ip/system_out_mux_1_1/sim/system_out_mux_1_1.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlslice_v1_0_2 $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/system/ipshared/a40c" +incdir+"$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/a40c" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/11d0/hdl/xlslice_v1_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/system/ipshared/a40c" +incdir+"$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/a40c" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_tdd_ch_slice_0_0/sim/system_tdd_ch_slice_0_0.v" \
    "$ref_dir/../../../bd/system/ip/system_tdd_ch_slice_1_0/sim/system_tdd_ch_slice_1_0.v" \
    "$ref_dir/../../../bd/system/ip/system_tdd_ch_slice_2_0/sim/system_tdd_ch_slice_2_0.v" \
    "$ref_dir/../../../bd/system/ipshared/util_cdc/sync_bits.v" \
    "$ref_dir/../../../bd/system/ipshared/util_cdc/sync_data.v" \
    "$ref_dir/../../../bd/system/ipshared/util_cdc/sync_event.v" \
    "$ref_dir/../../../bd/system/ipshared/common/up_axi.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../bd/system/ipshared/a40c" +incdir+"$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/a40c" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ipshared/3c1a/axi_tdd_pkg.sv" \
    "$ref_dir/../../../bd/system/ipshared/3c1a/axi_tdd_channel.sv" \
    "$ref_dir/../../../bd/system/ipshared/3c1a/axi_tdd_counter.sv" \
    "$ref_dir/../../../bd/system/ipshared/3c1a/axi_tdd_regmap.sv" \
    "$ref_dir/../../../bd/system/ipshared/3c1a/axi_tdd_sync_gen.sv" \
    "$ref_dir/../../../bd/system/ipshared/3c1a/axi_tdd.sv" \
    "$ref_dir/../../../bd/system/ip/system_tdd_core_0/sim/system_tdd_core_0.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconstant_v1_1_7 $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/system/ipshared/a40c" +incdir+"$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/a40c" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/badb/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/system/ipshared/a40c" +incdir+"$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/a40c" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_GND_1_0/sim/system_GND_1_0.v" \
    "$ref_dir/../../../bd/system/ip/system_GND_32_0/sim/system_GND_32_0.v" \
    "$ref_dir/../../../bd/system/ip/system_VCC_1_0/sim/system_VCC_1_0.v" \
    "$ref_dir/../../../bd/system/ipshared/common/ad_addsub.v" \
    "$ref_dir/../../../bd/system/ipshared/xilinx/common/ad_data_clk.v" \
    "$ref_dir/../../../bd/system/ipshared/xilinx/common/ad_data_in.v" \
    "$ref_dir/../../../bd/system/ipshared/xilinx/common/ad_data_out.v" \
    "$ref_dir/../../../bd/system/ipshared/common/ad_datafmt.v" \
    "$ref_dir/../../../bd/system/ipshared/xilinx/common/ad_dcfilter.v" \
    "$ref_dir/../../../bd/system/ipshared/common/ad_dds.v" \
    "$ref_dir/../../../bd/system/ipshared/common/ad_dds_1.v" \
    "$ref_dir/../../../bd/system/ipshared/common/ad_dds_2.v" \
    "$ref_dir/../../../bd/system/ipshared/common/ad_dds_cordic_pipe.v" \
    "$ref_dir/../../../bd/system/ipshared/common/ad_dds_sine.v" \
    "$ref_dir/../../../bd/system/ipshared/common/ad_dds_sine_cordic.v" \
    "$ref_dir/../../../bd/system/ipshared/common/ad_iqcor.v" \
    "$ref_dir/../../../bd/system/ipshared/xilinx/common/ad_mul.v" \
    "$ref_dir/../../../bd/system/ipshared/common/ad_pnmon.v" \
    "$ref_dir/../../../bd/system/ipshared/common/ad_pps_receiver.v" \
    "$ref_dir/../../../bd/system/ipshared/common/ad_rst.v" \
    "$ref_dir/../../../bd/system/ipshared/common/ad_tdd_control.v" \
    "$ref_dir/../../../bd/system/ipshared/519b/xilinx/axi_ad9361_cmos_if.v" \
    "$ref_dir/../../../bd/system/ipshared/519b/xilinx/axi_ad9361_lvds_if.v" \
    "$ref_dir/../../../bd/system/ipshared/519b/axi_ad9361_rx.v" \
    "$ref_dir/../../../bd/system/ipshared/519b/axi_ad9361_rx_channel.v" \
    "$ref_dir/../../../bd/system/ipshared/519b/axi_ad9361_rx_pnmon.v" \
    "$ref_dir/../../../bd/system/ipshared/519b/axi_ad9361_tdd.v" \
    "$ref_dir/../../../bd/system/ipshared/519b/axi_ad9361_tdd_if.v" \
    "$ref_dir/../../../bd/system/ipshared/519b/axi_ad9361_tx.v" \
    "$ref_dir/../../../bd/system/ipshared/519b/axi_ad9361_tx_channel.v" \
    "$ref_dir/../../../bd/system/ipshared/common/up_adc_channel.v" \
    "$ref_dir/../../../bd/system/ipshared/common/up_adc_common.v" \
    "$ref_dir/../../../bd/system/ipshared/common/up_clock_mon.v" \
    "$ref_dir/../../../bd/system/ipshared/common/up_dac_channel.v" \
    "$ref_dir/../../../bd/system/ipshared/common/up_dac_common.v" \
    "$ref_dir/../../../bd/system/ipshared/common/up_delay_cntrl.v" \
    "$ref_dir/../../../bd/system/ipshared/common/up_tdd_cntrl.v" \
    "$ref_dir/../../../bd/system/ipshared/common/up_xfer_cntrl.v" \
    "$ref_dir/../../../bd/system/ipshared/common/up_xfer_status.v" \
    "$ref_dir/../../../bd/system/ipshared/519b/axi_ad9361.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ad9361_0/sim/system_axi_ad9361_0.v" \
    "$ref_dir/../../../bd/system/ipshared/5013/sync_gray.v" \
    "$ref_dir/../../../bd/system/ipshared/common/ad_mem.v" \
    "$ref_dir/../../../bd/system/ipshared/8e37/util_axis_fifo_address_generator.v" \
    "$ref_dir/../../../bd/system/ipshared/8e37/util_axis_fifo.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../bd/system/ipshared/a40c" +incdir+"$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/a40c" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_axi_ad9361_adc_dma_0/sim/system_axi_ad9361_adc_dma_0_pkg.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/system/ipshared/a40c" +incdir+"$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/a40c" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ipshared/common/ad_mem_asym.v" \
    "$ref_dir/../../../bd/system/ipshared/a40c/address_generator.v" \
    "$ref_dir/../../../bd/system/ipshared/a40c/axi_dmac_burst_memory.v" \
    "$ref_dir/../../../bd/system/ipshared/a40c/axi_dmac_regmap.v" \
    "$ref_dir/../../../bd/system/ipshared/a40c/axi_dmac_regmap_request.v" \
    "$ref_dir/../../../bd/system/ipshared/a40c/axi_dmac_reset_manager.v" \
    "$ref_dir/../../../bd/system/ipshared/a40c/axi_dmac_resize_dest.v" \
    "$ref_dir/../../../bd/system/ipshared/a40c/axi_dmac_resize_src.v" \
    "$ref_dir/../../../bd/system/ipshared/a40c/axi_dmac_response_manager.v" \
    "$ref_dir/../../../bd/system/ipshared/a40c/axi_dmac_transfer.v" \
    "$ref_dir/../../../bd/system/ipshared/a40c/axi_register_slice.v" \
    "$ref_dir/../../../bd/system/ipshared/a40c/data_mover.v" \
    "$ref_dir/../../../bd/system/ipshared/a40c/dest_axi_mm.v" \
    "$ref_dir/../../../bd/system/ipshared/a40c/dest_axi_stream.v" \
    "$ref_dir/../../../bd/system/ipshared/a40c/dest_fifo_inf.v" \
    "$ref_dir/../../../bd/system/ipshared/a40c/dmac_2d_transfer.v" \
    "$ref_dir/../../../bd/system/ipshared/a40c/request_arb.v" \
    "$ref_dir/../../../bd/system/ipshared/a40c/request_generator.v" \
    "$ref_dir/../../../bd/system/ipshared/a40c/response_generator.v" \
    "$ref_dir/../../../bd/system/ipshared/a40c/response_handler.v" \
    "$ref_dir/../../../bd/system/ipshared/a40c/splitter.v" \
    "$ref_dir/../../../bd/system/ipshared/a40c/src_axi_mm.v" \
    "$ref_dir/../../../bd/system/ipshared/a40c/src_axi_stream.v" \
    "$ref_dir/../../../bd/system/ipshared/a40c/src_fifo_inf.v" \
    "$ref_dir/../../../bd/system/ipshared/a40c/axi_dmac.v" \
    "$ref_dir/../../../bd/system/ip/system_axi_ad9361_adc_dma_0/sim/system_axi_ad9361_adc_dma_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../bd/system/ipshared/a40c" +incdir+"$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/a40c" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_axi_ad9361_dac_dma_0/sim/system_axi_ad9361_dac_dma_0_pkg.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/system/ipshared/a40c" +incdir+"$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/a40c" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_axi_ad9361_dac_dma_0/sim/system_axi_ad9361_dac_dma_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/system/ipshared/a40c" +incdir+"$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/a40c" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/system/ipshared/a40c" +incdir+"$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/a40c" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_27 $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/system/ipshared/a40c" +incdir+"$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/a40c" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/f0b4/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work fifo_generator_v13_2_7 $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/system/ipshared/a40c" +incdir+"$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/a40c" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/83df/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_7 $vhdlan_opts \
    "$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/83df/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_7 $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/system/ipshared/a40c" +incdir+"$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/a40c" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/83df/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_26 $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/system/ipshared/a40c" +incdir+"$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/a40c" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/3111/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_28 $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/system/ipshared/a40c" +incdir+"$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/a40c" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/c40e/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/system/ipshared/a40c" +incdir+"$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/a40c" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_xbar_0/sim/system_xbar_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_pkg_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_lite_ipif_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work interrupt_control_v3_1_4 $vhdlan_opts \
    "$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/a040/hdl/interrupt_control_v3_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_iic_v2_1_3 $vhdlan_opts \
    "$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/1439/hdl/axi_iic_v2_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_axi_iic_main_0/sim/system_axi_iic_main_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work dist_mem_gen_v8_0_13 $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/system/ipshared/a40c" +incdir+"$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/a40c" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/0bf5/simulation/dist_mem_gen_v8_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_srl_fifo_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/51ce/hdl/lib_srl_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_fifo_v1_0_16 $vhdlan_opts \
    "$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/6c82/hdl/lib_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_quad_spi_v3_2_26 $vhdlan_opts \
    "$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/75b9/hdl/axi_quad_spi_v3_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_axi_spi_0/sim/system_axi_spi_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/system/ipshared/a40c" +incdir+"$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/a40c" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/common/ad_perfect_shuffle.v" \
    "$ref_dir/../../../bd/system/ipshared/util_pack_common/pack_ctrl.v" \
    "$ref_dir/../../../bd/system/ipshared/util_pack_common/pack_interconnect.v" \
    "$ref_dir/../../../bd/system/ipshared/util_pack_common/pack_network.v" \
    "$ref_dir/../../../bd/system/ipshared/util_pack_common/pack_shell.v" \
    "$ref_dir/../../../bd/system/ipshared/3c20/util_cpack2_impl.v" \
    "$ref_dir/../../../bd/system/ipshared/3c20/util_cpack2.v" \
    "$ref_dir/../../../bd/system/ip/system_cpack_0/sim/system_cpack_0.v" \
    "$ref_dir/../../../bd/system/ip/system_decim_slice_0/sim/system_decim_slice_0.v" \
    "$ref_dir/../../../bd/system/ip/system_interp_slice_0/sim/system_interp_slice_0.v" \
    "$ref_dir/../../../bd/system/ip/system_logic_inv_0/sim/system_logic_inv_0.v" \
    "$ref_dir/../../../bd/system/ip/system_logic_or_0/sim/system_logic_or_0.v" \
    "$ref_dir/../../../bd/system/ip/system_logic_or_1_0/sim/system_logic_or_1_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconcat_v2_1_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/system/ipshared/a40c" +incdir+"$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/a40c" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/4b67/hdl/xlconcat_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/system/ipshared/a40c" +incdir+"$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/a40c" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_sys_concat_intc_0/sim/system_sys_concat_intc_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_vip_v1_1_13 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../bd/system/ipshared/a40c" +incdir+"$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/a40c" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/ffc2/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work processing_system7_vip_v1_0_15 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../bd/system/ipshared/a40c" +incdir+"$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/a40c" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/ee60/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/system/ipshared/a40c" +incdir+"$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/a40c" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_sys_ps7_0/sim/system_sys_ps7_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work proc_sys_reset_v5_0_13 $vhdlan_opts \
    "$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/system/ip/system_sys_rstgen_0/sim/system_sys_rstgen_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/system/ipshared/a40c" +incdir+"$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/a40c" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ipshared/85da/util_upack2_impl.v" \
    "$ref_dir/../../../bd/system/ipshared/85da/util_upack2.v" \
    "$ref_dir/../../../bd/system/ip/system_tx_upack_0/sim/system_tx_upack_0.v" \
    "$ref_dir/../../../bd/system/sim/system.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_converter_v2_1_27 $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/system/ipshared/a40c" +incdir+"$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/a40c" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/aeb3/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../bd/system/ipshared/a40c" +incdir+"$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/ee60/hdl" +incdir+"$ref_dir/../../../../tjd.gen/sources_1/bd/system/ipshared/a40c" +incdir+"/tools/Xilinx/Vivado/2022.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/system/ip/system_auto_pc_0/sim/system_auto_pc_0.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log
}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.system xil_defaultlib.glbl -o system_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./system_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./system.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  else
    lib_map_path="/home/raincorn/pluto/plutosdr-fw/hdl/projects/tjd/tjd.cache/compile_simlib/vcs"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key system_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc system_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./system.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: system.sh [-help]\n\
Usage: system.sh [-lib_map_path]\n\
Usage: system.sh [-reset_run]\n\
Usage: system.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
