# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/raincorn/pluto/plutosdr-fw/hdl/projects/tjd/tjd.srcs/sources_1/bd/system/ip/system_tdd_core_0/system_tdd_core_0.xci
# IP: The module: 'system_tdd_core_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/raincorn/pluto/plutosdr-fw/hdl/projects/tjd/tjd.gen/sources_1/bd/system/ip/system_tdd_core_0/system_tdd_core_0_constr.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_tdd_core_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/raincorn/pluto/plutosdr-fw/hdl/projects/tjd/tjd.srcs/sources_1/bd/system/ip/system_tdd_core_0/system_tdd_core_0.xci
# IP: The module: 'system_tdd_core_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/raincorn/pluto/plutosdr-fw/hdl/projects/tjd/tjd.gen/sources_1/bd/system/ip/system_tdd_core_0/system_tdd_core_0_constr.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_tdd_core_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
