# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/raincorn/pluto/plutosdr-fw/hdl/projects/tjd/tjd.srcs/sources_1/bd/system/ip/system_fir_interpolation_1_0/system_fir_interpolation_1_0.xci
# IP: The module: 'system_fir_interpolation_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/raincorn/pluto/plutosdr-fw/hdl/projects/tjd/tjd.gen/sources_1/bd/system/ip/system_fir_interpolation_1_0/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_fir_interpolation_1_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/raincorn/pluto/plutosdr-fw/hdl/projects/tjd/tjd.gen/sources_1/bd/system/ip/system_fir_interpolation_1_0/system_fir_interpolation_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_fir_interpolation_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/raincorn/pluto/plutosdr-fw/hdl/projects/tjd/tjd.srcs/sources_1/bd/system/ip/system_fir_interpolation_1_0/system_fir_interpolation_1_0.xci
# IP: The module: 'system_fir_interpolation_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/raincorn/pluto/plutosdr-fw/hdl/projects/tjd/tjd.gen/sources_1/bd/system/ip/system_fir_interpolation_1_0/constraints/fir_compiler_v7_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_fir_interpolation_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/raincorn/pluto/plutosdr-fw/hdl/projects/tjd/tjd.gen/sources_1/bd/system/ip/system_fir_interpolation_1_0/system_fir_interpolation_1_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_fir_interpolation_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
